### ISSUE TITLE
Using Api Compability 4.x throw errors

### ISSUE THREAD

**Issue by psydack** [KuraiAndras/NumericsConverter#3]
The code throw the follow error when  I use API Compability Level .NET 4.x.

`The type or namespace name 'Vector<>' does not exist in the namespace 'System.Numerics' (are you missing an assembly reference?).`

This is intended?
For while I put **USE_DOTNET20** directive in some lines **ConverterExtension.cs**. Maybe has some better way to do with this.

**Comment by KuraiAndras** [comment]
I think the 4.x api does not contain the System.Numerics namespace. You should be able to download that from nuget and add it to your asset folder.

**Comment by KuraiAndras** [comment]
If you verified that it works, can you close this?

**Comment by psydack** [comment]
Yes, that worked, but that suggestion it's to not load any unnecessary library. Thanks.
